# Generated by Django 5.1.1 on 2024-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Welcome to the Homepage', max_length=200)),
                ('sub_title', models.TextField(default='This is the subtitle of the homepage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage_images/')),
            ],
        ),
    ]
