# Generated by Django 5.1.1 on 2024-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_aboutus_alter_homepagecontent_main_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
