# Generated by Django 5.1.1 on 2024-10-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_remove_aboutus_updated_at_alter_aboutus_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='title',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
