# Generated by Django 5.1.1 on 2024-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_remove_aboutus_title_alter_aboutus_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
