# Generated by Django 5.1.1 on 2024-10-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_aboutus_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourpeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=800, null=True)),
            ],
        ),
    ]
