# Generated by Django 5.1.1 on 2024-10-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_mission_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=800, null=True)),
            ],
        ),
    ]
