# Generated by Django 5.1.1 on 2024-10-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/images/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('location_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=20)),
                ('home_page_order', models.IntegerField(default=0)),
                ('brand_page_order', models.IntegerField(default=0)),
                ('reservation_url', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['home_page_order', 'brand_page_order'],
            },
        ),
    ]
