# Generated by Django 5.1.1 on 2024-10-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_manage_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_restaurant',
            name='brand_page_order',
            field=models.IntegerField(default=99, null=True),
        ),
        migrations.AlterField(
            model_name='manage_restaurant',
            name='home_page_order',
            field=models.IntegerField(default=99, null=True),
        ),
    ]
