# Generated by Django 5.1.1 on 2024-10-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_alter_manage_restaurant_brand_page_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_restaurant',
            name='Description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='homepage_images/')),
                ('manage_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rest.manage_restaurant')),
            ],
        ),
    ]
