# Generated by Django 5.1.1 on 2024-10-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_manage_restaurant_description_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage_restaurant',
            old_name='Description',
            new_name='description',
        ),
    ]
