# Generated by Django 5.1.1 on 2024-10-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_rename_description_manage_restaurant_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Images_rest',
        ),
    ]
