# Generated by Django 5.1.1 on 2024-10-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_rename_images_images_rest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_rest',
            old_name='manage_restaurant',
            new_name='restaurant_img',
        ),
    ]
