# Generated by Django 5.1.1 on 2024-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_rename_manage_restaurant_images_rest_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_restaurant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
