# Generated by Django 5.1.1 on 2024-10-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_alter_manage_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_restaurant',
            name='location_type',
            field=models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=20, null=True),
        ),
    ]
