# Generated by Django 5.1.1 on 2024-10-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_alter_manage_restaurant_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=800, null=True)),
                ('title', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
