# Generated by Django 5.1.1 on 2024-10-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_media_adm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='media_adm',
            new_name='Media_media',
        ),
    ]
