# Generated by Django 5.1.1 on 2024-10-31 11:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_rename_media_adm_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_media',
            name='content',
            field=tinymce.models.HTMLField(max_length=800, null=True),
        ),
    ]
