# Generated by Django 5.1.1 on 2024-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_alter_media_media_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
