# Generated by Django 5.1.1 on 2024-11-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=800, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=255, null=True)),
            ],
        ),
    ]
