# Generated by Django 5.1.1 on 2024-11-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_careers_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careers_us',
            old_name='Employement_Type',
            new_name='employement_Type',
        ),
    ]
