# Generated by Django 5.1.1 on 2024-11-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_rename_employement_type_careers_us_employement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers_us',
            name='employement_Type',
        ),
        migrations.AddField(
            model_name='careers_us',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('none', 'None')], max_length=35, null=True),
        ),
    ]
