# Generated by Django 5.1.1 on 2024-11-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_remove_careers_us_employement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(max_length=70, null=True)),
                ('position', models.CharField(max_length=20, null=True)),
                ('cv', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
